apiVersion: v1
kind: Service
metadata:
  name: discord-assistant
  namespace: '{{"NAMESPACE" | env}}'
spec:
  selector:
    app: discord-assistant
  ports:
    - name: http
      port: 8080
      targetPort: http
